theme: jekyll-theme-chirpy
title: Hannah Dattilo 
description: Webpage for Hannah Dattilo, Electrical Engineering PhD student at Vanderbilt University

baseurl: "/hannahdattilo/hannahdattilo.github.io" # the subpath of your site, e.g. /blog
url: "https://github.com" # the base hostname & protocol for your site, e.g. http://example.com

plugins:
  - jekyll-feed
  - jekyll-timeago
