#remote_theme: jekyll-theme-chirpy
#theme: jekyll-theme-cayman
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

# title: Hannah Dattilo 
title: hi
description: Webpage for Hannah Dattilo, Electrical Engineering PhD student at Vanderbilt University

#baseurl: "/hannahdattilo/hannahdattilo.github.io" # the subpath of your site, e.g. /blog
#url: "https://github.com" # the base hostname & protocol for your site, e.g. http://example.com

